import { useState, useRef, useEffect } from 'react';
import { router } from '@inertiajs/react';
import { Input, Button, Icons } from '../../components/ui';
import { useToast } from '../../components/ui/Toast';
import { theme } from '../../lib/theme';
import { risks, countries, industries, generateId, type Organization, type OrgWebsite } from '../../mock/organizations';
import { mockPersons, contactTypes, contactStatuses, type PersonEmail, type PersonPhone, type PersonAddress, type PersonNote } from '../../mock/persons';

const Label = ({ children }: { children: string }) => <label style={{ display:'block', fontSize:10, fontWeight:600, color:theme.textSecondary, marginBottom:5, letterSpacing:'0.08em', textTransform:'uppercase' as const }}>{children}</label>;
const Sel = ({ value, onChange, options, placeholder }: { value:string; onChange:(v:string)=>void; options:string[]; placeholder?:string }) => <select value={value} onChange={e=>onChange(e.target.value)} style={{ width:'100%', padding:'9px 12px', background:theme.bgInput, color:theme.text, border:`1px solid ${theme.border}`, borderRadius:6, fontSize:13, fontFamily:'inherit', outline:'none', cursor:'pointer' }}>{placeholder && <option value="">{placeholder}</option>}{options.map(o=><option key={o} value={o}>{o}</option>)}</select>;
function SearchSel({ value, onChange, options, placeholder }: { value:string; onChange:(v:string)=>void; options:string[]; placeholder:string }) { const [open,setOpen]=useState(false); const [q,setQ]=useState(''); const ref=useRef<HTMLDivElement>(null); useEffect(()=>{const h=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false);};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h);},[]);const f=options.filter(o=>o.toLowerCase().includes(q.toLowerCase()));return<div ref={ref} style={{position:'relative'}}><button onClick={()=>{setOpen(!open);setQ('');}} style={{width:'100%',padding:'9px 12px',background:theme.bgInput,color:value?theme.text:theme.textDim,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',cursor:'pointer',textAlign:'left' as const,display:'flex',justifyContent:'space-between'}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap' as const}}>{value||placeholder}</span><svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="1.5"><polyline points="2,4 5,7 8,4"/></svg></button>{open&&<div style={{position:'absolute',top:'100%',left:0,right:0,marginTop:4,background:'#0d1220',border:`1px solid ${theme.border}`,borderRadius:8,zIndex:50,maxHeight:200,display:'flex',flexDirection:'column',boxShadow:'0 8px 24px rgba(0,0,0,0.5)'}}><div style={{padding:'5px 6px',borderBottom:`1px solid ${theme.border}`}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..." autoFocus style={{width:'100%',padding:'5px 8px',background:theme.bgInput,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:4,fontSize:12,fontFamily:'inherit',outline:'none'}} /></div><div style={{overflowY:'auto',flex:1}}>{f.slice(0,60).map(o=><div key={o} onClick={()=>{onChange(o);setOpen(false);}} style={{padding:'6px 10px',cursor:'pointer',fontSize:12,color:value===o?theme.accent:theme.text}} onMouseEnter={e=>(e.currentTarget.style.background='rgba(128,128,128,0.08)')} onMouseLeave={e=>(e.currentTarget.style.background='transparent')}>{o}</div>)}</div></div>}</div>; }
function PersonSearchSel({ value, onChange, placeholder }: { value:string; onChange:(v:string)=>void; placeholder:string }) { const options = mockPersons.map(p=>`${p.firstName} ${p.lastName}`); return <SearchSel value={value} onChange={onChange} options={options} placeholder={placeholder} />; }
const AddBtn = ({ onClick, label }: { onClick:()=>void; label:string }) => <button onClick={onClick} style={{ display:'flex', alignItems:'center', gap:6, background:'none', border:`1px dashed ${theme.border}`, borderRadius:8, padding:'10px 16px', cursor:'pointer', color:theme.accent, fontSize:12, fontWeight:600, fontFamily:'inherit', width:'100%', justifyContent:'center' }}><svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="8" y1="3" x2="8" y2="13"/><line x1="3" y1="8" x2="13" y2="8"/></svg>{label}</button>;
const RemoveBtn = ({ onClick }: { onClick:()=>void }) => <button onClick={onClick} style={{ background:theme.dangerDim, border:'1px solid rgba(239,68,68,0.25)', borderRadius:5, padding:'3px 8px', cursor:'pointer', color:theme.danger, display:'flex', fontSize:10, fontWeight:600, fontFamily:'inherit', alignItems:'center', gap:3 }}><svg width="9" height="9" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="4" y1="4" x2="12" y2="12"/><line x1="12" y1="4" x2="4" y2="12"/></svg>Remove</button>;
const Card = ({ children }: { children:React.ReactNode }) => <div style={{ background:theme.bgInput, border:`1px solid ${theme.border}`, borderRadius:8, padding:14, marginBottom:10 }}>{children}</div>;

function ConfirmModal({ open, title, message, onConfirm, onCancel }: { open:boolean; title:string; message:string; onConfirm:()=>void; onCancel:()=>void }) { if(!open)return null; return(<div onClick={onCancel} style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.6)',zIndex:200,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}><div onClick={e=>e.stopPropagation()} style={{background:'#0d1220',border:`1px solid ${theme.border}`,borderRadius:14,width:'100%',maxWidth:400,padding:24,boxShadow:'0 20px 60px rgba(0,0,0,0.6)',animation:'argux-fadeIn 0.2s ease-out'}}><div style={{width:48,height:48,borderRadius:12,background:theme.dangerDim,display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 16px',color:theme.danger}}><svg width="24" height="24" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M7.13 2.5a1 1 0 011.74 0l5.5 9.5A1 1 0 0113.5 13.5h-11a1 1 0 01-.87-1.5z"/><line x1="8" y1="6" x2="8" y2="8.5"/><circle cx="8" cy="10.5" r="0.5" fill="currentColor"/></svg></div><h3 style={{fontSize:16,fontWeight:700,color:theme.text,textAlign:'center',margin:'0 0 8px'}}>{title}</h3><p style={{fontSize:13,color:theme.textSecondary,textAlign:'center',lineHeight:1.6,margin:'0 0 24px'}}>{message}</p><div style={{display:'flex',gap:10}}><Button variant="secondary" onClick={onCancel} style={{flex:1}}>Cancel</Button><Button variant="danger" onClick={onConfirm} style={{flex:1}}>Delete</Button></div></div></div>); }

type FTab = 'basic' | 'contacts' | 'social' | 'address' | 'notes';
const ftabs: { id:FTab; label:string; icon:React.ReactNode }[] = [
    { id:'basic', label:'Basic Info', icon:Icons.user(14) },
    { id:'contacts', label:'Contacts', icon:Icons.mail(14) },
    { id:'social', label:'Social', icon:<svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><circle cx="4" cy="8" r="2"/><circle cx="12" cy="4" r="2"/><circle cx="12" cy="12" r="2"/><line x1="5.8" y1="7" x2="10.2" y2="5"/><line x1="5.8" y1="9" x2="10.2" y2="11"/></svg> },
    { id:'address', label:'Addresses', icon:<svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M8 1C5.24 1 3 3.24 3 6c0 4.5 5 9 5 9s5-4.5 5-9c0-2.76-2.24-5-5-5z"/><circle cx="8" cy="6" r="2"/></svg> },
    { id:'notes', label:'Notes', icon:<svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M10 1H4a1 1 0 00-1 1v12a1 1 0 001 1h8a1 1 0 001-1V4z"/><polyline points="10,1 10,4 13,4"/></svg> },
];

export default function OrgForm({ org, mode }: { org?:Organization; mode:'create'|'edit' }) {
    const toast = useToast();
    const [tab, setTab] = useState<FTab>('basic');
    const [loading, setLoading] = useState(false);
    const [logo, setLogo] = useState<string|null>(org?.logo||null);
    const [deleteNoteIdx, setDeleteNoteIdx] = useState<number|null>(null);

    const [name, setName] = useState(org?.name||'');
    const [vat, setVat] = useState(org?.vat||'');
    const [taxNumber, setTaxNumber] = useState(org?.taxNumber||'');
    const [owner, setOwner] = useState(org?.owner||'');
    const [ceo, setCeo] = useState(org?.ceo||'');
    const [industry, setIndustry] = useState(org?.industry||'');
    const [risk, setRisk] = useState(org?.risk||'');
    const [websites, setWebsites] = useState<OrgWebsite[]>(org?.websites||[]);
    const [emails, setEmails] = useState<PersonEmail[]>(org?.emails||[]);
    const [phones, setPhones] = useState<PersonPhone[]>(org?.phones||[]);
    const platforms = ['Facebook','LinkedIn','Instagram','TikTok','Snapchat','YouTube'];
    const [socials, setSocials] = useState<Record<string,{id:string;url:string}[]>>(Object.fromEntries(platforms.map(p=>[p,org?.socials.find(s=>s.platform===p)?.profiles||[]])));
    const [addresses, setAddresses] = useState<PersonAddress[]>(org?.addresses||[]);
    const [notes, setNotes] = useState<PersonNote[]>(org?.notes||[]);
    const [newNote, setNewNote] = useState('');
    const [editingNote, setEditingNote] = useState<string|null>(null);

    const handleLogoChange = (e:React.ChangeEvent<HTMLInputElement>) => { const f=e.target.files?.[0]; if(f){const r=new FileReader();r.onload=()=>setLogo(r.result as string);r.readAsDataURL(f);} };
    const handleSave = () => { if(!name){toast.error('Validation','Company name is required.');return;} setLoading(true); setTimeout(()=>{setLoading(false);toast.success(mode==='create'?'Organization created':'Organization updated',name);if(mode==='create')router.visit('/organizations');},1200); };
    const handleDeleteNote = () => { if(deleteNoteIdx!==null){setNotes(notes.filter((_,i)=>i!==deleteNoteIdx));setDeleteNoteIdx(null);toast.warning('Note deleted');} };

    return (<div style={{maxWidth:1000,margin:'0 auto'}}>
        <ConfirmModal open={deleteNoteIdx!==null} title="Delete Note" message="Delete this note? This cannot be undone." onConfirm={handleDeleteNote} onCancel={()=>setDeleteNoteIdx(null)} />

        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20,flexWrap:'wrap',gap:12}}>
            <div><h1 style={{fontSize:20,fontWeight:700,color:theme.text,margin:'0 0 4px'}}>{mode==='create'?'Add New Organization':`Edit: ${org?.name}`}</h1><p style={{fontSize:12,color:theme.textSecondary,margin:0}}>Fill in organization information.</p></div>
            <div style={{display:'flex',gap:8}}><Button variant="secondary" onClick={()=>router.visit('/organizations')} style={{width:'auto',padding:'9px 18px',fontSize:11}}>Cancel</Button><Button onClick={handleSave} loading={loading} style={{width:'auto',padding:'9px 22px',fontSize:11}}>{mode==='create'?'Create':'Save'}</Button></div>
        </div>

        <style>{`@media(max-width:768px){.of-vtabs{display:none!important}.of-htabs{display:flex!important}.of-layout{flex-direction:column!important}}`}</style>

        <div className="of-layout" style={{display:'flex',gap:20,alignItems:'flex-start'}}>
            <div className="of-vtabs" style={{width:170,flexShrink:0,position:'sticky',top:80,display:'flex',flexDirection:'column',gap:3}}>
                {ftabs.map(t=>{const a=tab===t.id;return<button key={t.id} onClick={()=>setTab(t.id)} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 14px',borderRadius:8,cursor:'pointer',fontFamily:'inherit',fontSize:13,fontWeight:a?600:400,color:a?theme.accent:theme.textSecondary,background:a?theme.accentDim:'transparent',border:'none',textAlign:'left' as const,width:'100%'}}><span style={{display:'flex',color:a?theme.accent:theme.textDim}}>{t.icon}</span>{t.label}</button>;})}
            </div>
            <div className="of-htabs" style={{display:'none',gap:2,marginBottom:16,borderBottom:`1px solid ${theme.border}`,overflowX:'auto',width:'100%',scrollbarWidth:'none' as const}}>
                {ftabs.map(t=>{const a=tab===t.id;return<button key={t.id} onClick={()=>setTab(t.id)} style={{background:'none',border:'none',borderBottom:`2px solid ${a?theme.accent:'transparent'}`,padding:'8px 14px',cursor:'pointer',fontFamily:'inherit',color:a?theme.text:theme.textSecondary,fontSize:12,fontWeight:a?700:500,whiteSpace:'nowrap' as const,flexShrink:0}}>{t.label}</button>;})}
            </div>

            <div style={{flex:1,minWidth:0,animation:'argux-fadeIn 0.2s ease-out'}}>
                {tab==='basic' && <>
                    <div style={{display:'flex',alignItems:'center',gap:20,marginBottom:24,flexWrap:'wrap'}}>
                        <div style={{position:'relative'}}><div style={{width:72,height:72,borderRadius:12,overflow:'hidden',background:logo?'transparent':`linear-gradient(135deg, ${theme.accent}, ${theme.accent}80)`,display:'flex',alignItems:'center',justifyContent:'center',border:`3px solid ${theme.border}`}}>{logo ? <img src={logo} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}} /> : <span style={{fontSize:20,fontWeight:700,color:'#fff'}}>{name?.slice(0,2)||'??'}</span>}</div><label style={{position:'absolute',bottom:-2,right:-2,width:26,height:26,borderRadius:'50%',background:theme.accent,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',border:`2px solid ${theme.bg}`}}><svg width="11" height="11" viewBox="0 0 16 16" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round"><path d="M12 2l2 2-8 8H4v-2z"/></svg><input type="file" accept="image/*" onChange={handleLogoChange} style={{display:'none'}} /></label></div>
                        <div style={{fontSize:12,color:theme.textSecondary}}>Upload company logo<br/>JPG/PNG, max 5MB</div>
                    </div>
                    <Input label="Company Name *" value={name} onChange={e=>setName(e.target.value)} placeholder="Organization name" />
                    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(200px, 1fr))',gap:14,marginBottom:16}}>
                        <Input label="VAT Number" value={vat} onChange={e=>setVat(e.target.value)} placeholder="VAT ID" />
                        <Input label="Tax Number" value={taxNumber} onChange={e=>setTaxNumber(e.target.value)} placeholder="Tax ID" />
                        <div><Label>Industry</Label><SearchSel value={industry} onChange={setIndustry} options={industries} placeholder="Select industry" /></div>
                        <div><Label>Risk Level</Label><Sel value={risk} onChange={setRisk} options={[...risks]} placeholder="Select" /></div>
                    </div>
                    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(200px, 1fr))',gap:14,marginBottom:16}}>
                        <div><Label>CEO</Label><PersonSearchSel value={ceo} onChange={setCeo} placeholder="Search person or type name" /></div>
                        <div><Label>Owner</Label><PersonSearchSel value={owner} onChange={setOwner} placeholder="Search person or type name" /></div>
                    </div>
                    <h3 style={{fontSize:13,fontWeight:700,color:theme.text,marginBottom:10}}>Websites</h3>
                    {websites.map((w,i)=><div key={w.id} style={{display:'flex',gap:8,marginBottom:8}}><input value={w.url} onChange={e=>{const n=[...websites];n[i]={...n[i],url:e.target.value};setWebsites(n);}} placeholder="https://company.com" style={{flex:1,padding:'8px 12px',background:theme.bgInput,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none',minWidth:0}} /><RemoveBtn onClick={()=>setWebsites(websites.filter((_,j)=>j!==i))} /></div>)}
                    <AddBtn onClick={()=>setWebsites([...websites,{id:generateId(),url:''}])} label="Add Website" />
                </>}

                {tab==='contacts' && <>
                    <h3 style={{fontSize:14,fontWeight:700,color:theme.text,marginBottom:10}}>Email Addresses</h3>
                    {emails.map((em,i)=><Card key={em.id}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(150px, 1fr))',gap:10,marginBottom:8}}><div style={{gridColumn:'span 2'}}><Label>Email</Label><input value={em.email} onChange={e=>{const n=[...emails];n[i]={...n[i],email:e.target.value};setEmails(n);}} placeholder="email@company.com" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div><div><Label>Type</Label><Sel value={em.type} onChange={v=>{const n=[...emails];n[i]={...n[i],type:v};setEmails(n);}} options={[...contactTypes]} placeholder="Type" /></div><div><Label>Status</Label><Sel value={em.status} onChange={v=>{const n=[...emails];n[i]={...n[i],status:v};setEmails(n);}} options={[...contactStatuses]} placeholder="Status" /></div></div><div style={{display:'flex',gap:10,alignItems:'flex-end'}}><div style={{flex:1}}><Label>Notes</Label><input value={em.notes} onChange={e=>{const n=[...emails];n[i]={...n[i],notes:e.target.value};setEmails(n);}} placeholder="Notes" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div><RemoveBtn onClick={()=>setEmails(emails.filter((_,j)=>j!==i))} /></div></Card>)}
                    <AddBtn onClick={()=>setEmails([...emails,{id:generateId(),email:'',notes:'',type:'Business',status:'Active'}])} label="Add Email" />
                    <h3 style={{fontSize:14,fontWeight:700,color:theme.text,margin:'24px 0 10px'}}>Phone Numbers</h3>
                    {phones.map((ph,i)=><Card key={ph.id}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(150px, 1fr))',gap:10,marginBottom:8}}><div style={{gridColumn:'span 2'}}><Label>Phone</Label><input value={ph.number} onChange={e=>{const n=[...phones];n[i]={...n[i],number:e.target.value};setPhones(n);}} placeholder="+1 234 567 8900" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:"'JetBrains Mono',monospace",outline:'none'}} /></div><div><Label>Type</Label><Sel value={ph.type} onChange={v=>{const n=[...phones];n[i]={...n[i],type:v};setPhones(n);}} options={[...contactTypes]} placeholder="Type" /></div><div><Label>Status</Label><Sel value={ph.status} onChange={v=>{const n=[...phones];n[i]={...n[i],status:v};setPhones(n);}} options={[...contactStatuses]} placeholder="Status" /></div></div><div style={{display:'flex',gap:10,alignItems:'flex-end'}}><div style={{flex:1}}><Label>Notes</Label><input value={ph.notes} onChange={e=>{const n=[...phones];n[i]={...n[i],notes:e.target.value};setPhones(n);}} placeholder="Notes" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div><RemoveBtn onClick={()=>setPhones(phones.filter((_,j)=>j!==i))} /></div></Card>)}
                    <AddBtn onClick={()=>setPhones([...phones,{id:generateId(),number:'',notes:'',type:'Business',status:'Active',isWhatsApp:false,isWeChat:false,isTelegram:false,isSignal:false,isViber:false}])} label="Add Phone" />
                </>}

                {tab==='social' && <>{platforms.map(platform=><div key={platform} style={{marginBottom:18}}><h3 style={{fontSize:13,fontWeight:700,color:theme.text,marginBottom:8,display:'flex',alignItems:'center',gap:8}}><span style={{width:22,height:22,borderRadius:5,background:theme.accentDim,display:'flex',alignItems:'center',justifyContent:'center',fontSize:10,fontWeight:700,color:theme.accent}}>{platform[0]}</span>{platform}</h3>{(socials[platform]||[]).map((profile,i)=><div key={profile.id} style={{display:'flex',gap:8,marginBottom:8}}><input value={profile.url} onChange={e=>{const n={...socials};n[platform]=[...n[platform]];n[platform][i]={...n[platform][i],url:e.target.value};setSocials(n);}} placeholder={`https://${platform.toLowerCase()}.com/company`} style={{flex:1,padding:'8px 12px',background:theme.bgInput,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none',minWidth:0}} /><RemoveBtn onClick={()=>{const n={...socials};n[platform]=n[platform].filter((_,j)=>j!==i);setSocials(n);}} /></div>)}<AddBtn onClick={()=>{const n={...socials};n[platform]=[...(n[platform]||[]),{id:generateId(),url:''}];setSocials(n);}} label={`Add ${platform}`} /></div>)}</>}

                {tab==='address' && <>{addresses.map((addr,i)=><Card key={addr.id}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><span style={{fontSize:12,fontWeight:600,color:theme.textSecondary}}>Address #{i+1}</span><RemoveBtn onClick={()=>setAddresses(addresses.filter((_,j)=>j!==i))} /></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(160px, 1fr))',gap:10}}><div style={{gridColumn:'span 2'}}><Label>Street</Label><input value={addr.address} onChange={e=>{const n=[...addresses];n[i]={...n[i],address:e.target.value};setAddresses(n);}} placeholder="Street" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div>{[['addressNumber','Number','No.'],['zipCode','Zip','Zip'],['city','City','City']].map(([key,label,ph])=><div key={key}><Label>{label}</Label><input value={(addr as any)[key]} onChange={e=>{const n=[...addresses];(n[i] as any)[key]=e.target.value;setAddresses(n);}} placeholder={ph} style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div>)}<div><Label>Country</Label><SearchSel value={addr.country} onChange={v=>{const n=[...addresses];n[i]={...n[i],country:v};setAddresses(n);}} options={countries} placeholder="Select" /></div></div><div style={{marginTop:10}}><Label>Notes</Label><input value={addr.notes} onChange={e=>{const n=[...addresses];n[i]={...n[i],notes:e.target.value};setAddresses(n);}} placeholder="e.g. HQ, Branch" style={{width:'100%',padding:'8px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none'}} /></div></Card>)}<AddBtn onClick={()=>setAddresses([...addresses,{id:generateId(),address:'',addressNumber:'',zipCode:'',city:'',country:'',notes:''}])} label="Add Address" /></>}

                {tab==='notes' && <>
                    <textarea value={newNote} onChange={e=>setNewNote(e.target.value)} placeholder="Add intelligence note..." rows={3} style={{width:'100%',padding:'12px 14px',background:theme.bgInput,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:8,fontSize:13,fontFamily:'inherit',outline:'none',resize:'vertical',marginBottom:8}} />
                    <Button onClick={()=>{if(newNote.trim()){setNotes([{id:generateId(),text:newNote.trim(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},...notes]);setNewNote('');toast.success('Note added');}}} disabled={!newNote.trim()} style={{width:'auto',padding:'8px 20px',marginBottom:20}}>Add Note</Button>
                    {notes.length===0 ? <div style={{padding:'30px 16px',textAlign:'center',color:theme.textDim,fontSize:13}}>No notes yet.</div> : notes.map((note,i)=><Card key={note.id}>{editingNote===note.id ? <><textarea value={note.text} onChange={e=>{const n=[...notes];n[i]={...n[i],text:e.target.value,updatedAt:new Date().toISOString()};setNotes(n);}} rows={3} style={{width:'100%',padding:'10px 12px',background:theme.bg,color:theme.text,border:`1px solid ${theme.border}`,borderRadius:6,fontSize:13,fontFamily:'inherit',outline:'none',resize:'vertical',marginBottom:8}} /><Button onClick={()=>{setEditingNote(null);toast.success('Note updated');}} style={{width:'auto',padding:'6px 16px',fontSize:11}}>Save</Button></> : <><p style={{fontSize:13,color:theme.text,lineHeight:1.6,margin:'0 0 8px',whiteSpace:'pre-wrap' as const}}>{note.text}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:6}}><span style={{fontSize:10,color:theme.textDim}}>{new Date(note.updatedAt).toLocaleString()}</span><div style={{display:'flex',gap:6}}><button onClick={()=>setEditingNote(note.id)} style={{background:'none',border:`1px solid ${theme.border}`,borderRadius:4,padding:'3px 10px',fontSize:10,color:theme.textSecondary,cursor:'pointer',fontFamily:'inherit',fontWeight:600}}>Edit</button><button onClick={()=>setDeleteNoteIdx(i)} style={{background:theme.dangerDim,border:'1px solid rgba(239,68,68,0.25)',borderRadius:4,padding:'3px 10px',fontSize:10,color:theme.danger,cursor:'pointer',fontFamily:'inherit',fontWeight:600}}>Delete</button></div></div></>}</Card>)}
                </>}
            </div>
        </div>
    </div>);
}
